# Generated by Django 2.2.9 on 2020-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=20, verbose_name='코인명(한글)')),
                ('name_en', models.CharField(max_length=50, verbose_name='코인명(영어)')),
                ('code', models.CharField(max_length=20, verbose_name='코인 코드')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coin',
                'ordering': ['-name_ko'],
            },
        ),
    ]
