# Generated by Django 3.0.1 on 2020-01-08 14:16

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_price', models.IntegerField(default=0, verbose_name='기준가')),
                ('rise_value', models.IntegerField(default=0, verbose_name='상승 값')),
                ('rise_ratio', models.BooleanField(default=True, verbose_name='상승값 %여부')),
                ('fall_value', models.IntegerField(default=0, verbose_name='하락 값')),
                ('fall_ratio', models.BooleanField(default=True, verbose_name='하락 값 %여부')),
                ('buy_amount', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='매수량(1,2,3... 형태로 입력)')),
                ('bought_amount', models.IntegerField(default=0, verbose_name='총 매수량')),
                ('is_active', models.BooleanField(default=True, verbose_name='로직 실행')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='market.Coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_condition',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40, unique=True, verbose_name='주문 고유번호')),
                ('status', models.IntegerField(choices=[(0, '완료'), (1, '실패'), (2, '취소')], default=0, verbose_name='주무 상태')),
                ('type', models.IntegerField(choices=[(0, '매수'), (1, '매도')], verbose_name='주문 유형')),
                ('valance', models.FloatField(default=0.0, verbose_name='주문 개수')),
                ('price', models.FloatField(default=0.0, verbose_name='주문가')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='부가정보')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='transaction.OrderCondition')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
