# Generated by Django 3.0.1 on 2019-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercondition',
            name='stopped_at',
        ),
        migrations.AddField(
            model_name='ordercondition',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
